
paths:
  /memberMission/{userId}:
    get:
      tags:
        - MemberMission
      summary: 내가 진행중인 미션 조회 로직
      parameters:
        - name: userId
          in: path
          schema:
            type: integer
          required: true
        - name: missionId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
        - name: paging
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        '200':
          description: 리뷰 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "membermissionData": [
                    {
                      "member_id": 1,
                      "member_mission_id": 1,
                      "mission_id": 1,
                      "store_name": "가게이름",
                      "reward": 100,
                      "deadline": "2000.01.01",
                      "mission_spec": "미션 상세 어쩌구"
                    },
                    {
                      "member_id": 1,
                      "member_mission_id": 2,
                      "mission_id": 1,
                      "store_name": "가게이름",
                      "reward": 100,
                      "deadline": "2000.01.01",
                      "mission_spec": "미션 상세 어쩌구"
                    }
                  ],
                  "cursorId": 1
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.